server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.1:3306/yeomSK?serverTimezone=Asia/Seoul
    username: root
    password: 9939301a
  jpa:  
    hibernate:  
      ddl-auto: none  
    show-sql: true  
    properties:  
      hibernate:  
        format_sql: true
  kafka:
    bootstrap-servers: 192.168.56.1:9092
    consumer:
      group-id: foo
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
##게이트웨이 프로세스 추적
#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    reactor.netty.http.client: DEBUG
